language: go

os:
  - linux
  # - osx

# Container-based infrastructure
sudo: false

before_install:
  - go get -v golang.org/x/tools/cmd/stringer

script:
  - go run cmd/recipe/main.go -v -w 1 examples/all_tests.toml
