language: go

go:
  - "1.x"
  - master

os:
  - linux
  - osx

sudo: false

install:
- go get -v golang.org/x/tools/cmd/stringer

script:
- go test
- go run cmd/recipe/main.go -v -w 1 examples/all_tests.toml

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: 
      - $TRAVIS_OS_NAME = linux
      - $TRAVIS_GO_VERSION =~ ^1\.[0-9]+\.[0-9]+$
