language: go

os:
  - linux
  # - osx

# Container-based infrastructure
sudo: false

before_install:
  - go get -v golang.org/x/tools/cmd/stringer

script:
  - go run cmd/recipe/main.go -v examples/basic.json
  - go run cmd/recipe/main.go -v examples/basic.toml
  - go run cmd/recipe/main.go -v examples/parallel.json
  - go run cmd/recipe/main.go -v examples/parallel.toml
  - go run cmd/recipe/main.go -v examples/bootstrap.json
  - go run cmd/recipe/main.go -v examples/bootstrap.toml
