// Code generated by "stringer -type=TaskState"; DO NOT EDIT.

package recipe

import "strconv"

const _TaskState_name = "DisabledEnabledWaitingRunningSuccessFailure"

var _TaskState_index = [...]uint8{0, 8, 15, 22, 29, 36, 43}

func (i TaskState) String() string {
	if i < 0 || i >= TaskState(len(_TaskState_index)-1) {
		return "TaskState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskState_name[_TaskState_index[i]:_TaskState_index[i+1]]
}
