main = "t1"

[tasks.t1]
deps = ["t2", "t3",]
cmd = 'echo All done!!!'
stdout = ""
stderr = ""
allow_failure = false

[tasks.t2]
cmd = '''python -c "
import time
for i in range(10):
    time.sleep(0.5)
    print '{}: hi world'.format(i)
"'''

[tasks.t3]
cmd = '''python -c "
import time
time.sleep(2)
print 'Cancelling'
exit(1)
"'''
allow_failure = false
