main = "t1"

interp = ['python', '-c', '{cmd}']

[tasks.t1]
interp = ['/bin/sh', '-c', 'exec {cmd}']
deps = ["t2", "t3", "t4", "t5",]
cmd = 'echo All done!!!'

[tasks.t2]
cmd = '''
import time
for i in range(10):
    time.sleep(0.5)
    print '[t2] {}: hi world'.format(i)
'''

[tasks.t3]
cmd = '''
import time
for i in range(10):
    time.sleep(0.5)
    print '[t3] {}: hi world'.format(i)
'''

[tasks.t4]
cmd = '''
import time
for i in range(10):
    time.sleep(0.5)
    print '[t4] {}: hi world'.format(i)
'''

[tasks.t5]
cmd = '''
import time
for i in range(10):
    time.sleep(0.5)
    print '[t5] {}: hi world'.format(i)
'''
